/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.ssc;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int btn=0x7f020000;
        public static final int general_bg=0x7f020001;
        public static final int home_page_button=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int lower_left=0x7f020004;
        public static final int lower_right=0x7f020005;
        public static final int text=0x7f020006;
        public static final int title_back=0x7f020007;
        public static final int title_back_set_up=0x7f020008;
        public static final int title_bg=0x7f020009;
        public static final int upper_left=0x7f02000a;
        public static final int upper_right=0x7f02000b;
    }
    public static final class id {
        public static final int ET1=0x7f080049;
        public static final int ET2=0x7f08004b;
        public static final int TV1=0x7f08004a;
        public static final int TV2=0x7f08004d;
        public static final int action_settings=0x7f080093;
        public static final int btn=0x7f08004c;
        public static final int btset=0x7f08004f;
        public static final int course_detail=0x7f080002;
        public static final int courseselectETcTV1=0x7f080058;
        public static final int coursdeleteET=0x7f080005;
        public static final int coursdeleteTV1=0x7f080003;
        public static final int coursdeleteTV2=0x7f080004;
        public static final int coursdeletebtn=0x7f080006;
        public static final int coursinsertET1=0x7f08001f;
        public static final int coursinsertET2=0x7f080028;
        public static final int coursinsertET3=0x7f080027;
        public static final int coursinsertET4=0x7f080026;
        public static final int coursinsertET5=0x7f080025;
        public static final int coursinsertET6=0x7f080022;
        public static final int coursinsertTV0=0x7f08001c;
        public static final int coursinsertTV1=0x7f08001e;
        public static final int coursinsertTV2=0x7f080020;
        public static final int coursinsertTV3=0x7f080029;
        public static final int coursinsertTV4=0x7f08001d;
        public static final int coursinsertTV5=0x7f080024;
        public static final int coursinsertTV6=0x7f080021;
        public static final int coursinsertbtn=0x7f080023;
        public static final int coursselectET=0x7f08005a;
        public static final int coursselectTV2=0x7f080059;
        public static final int coursselectTV3=0x7f08005c;
        public static final int coursselectbtn=0x7f08005b;
        public static final int coursupdateET1=0x7f08006e;
        public static final int coursupdateET2=0x7f08006b;
        public static final int coursupdateET3=0x7f08006c;
        public static final int coursupdateET4=0x7f08006d;
        public static final int coursupdateET5=0x7f080072;
        public static final int coursupdateET6=0x7f080074;
        public static final int coursupdateTV0=0x7f080069;
        public static final int coursupdateTV1=0x7f080068;
        public static final int coursupdateTV2=0x7f08006a;
        public static final int coursupdateTV3=0x7f08006f;
        public static final int coursupdateTV5=0x7f080071;
        public static final int coursupdateTV6=0x7f080073;
        public static final int coursupdateTV7=0x7f080070;
        public static final int coursupdatebtn=0x7f080075;
        public static final int fanhui=0x7f080056;
        public static final int handle=0x7f080001;
        public static final int home_title=0x7f08004e;
        public static final int info_handle_btn=0x7f080054;
        public static final int kaitou=0x7f080055;
        public static final int listviews=0x7f080057;
        public static final int menuTV=0x7f08000f;
        public static final int menubtn1=0x7f080013;
        public static final int menubtn10=0x7f080018;
        public static final int menubtn11=0x7f08001a;
        public static final int menubtn12=0x7f08001b;
        public static final int menubtn2=0x7f080014;
        public static final int menubtn3=0x7f080012;
        public static final int menubtn4=0x7f080015;
        public static final int menubtn5=0x7f080010;
        public static final int menubtn6=0x7f080017;
        public static final int menubtn7=0x7f080011;
        public static final int menubtn8=0x7f080016;
        public static final int menubtn9=0x7f080019;
        public static final int my_cours=0x7f080051;
        public static final int select_cours=0x7f080053;
        public static final int show_cours=0x7f080050;
        public static final int show_teacher=0x7f080052;
        public static final int studeleteET=0x7f080009;
        public static final int studeleteTV1=0x7f080007;
        public static final int studeleteTV2=0x7f080008;
        public static final int studeletebtn=0x7f08000a;
        public static final int stuinsertET1=0x7f08002d;
        public static final int stuinsertET2=0x7f080036;
        public static final int stuinsertET3=0x7f080035;
        public static final int stuinsertET4=0x7f080034;
        public static final int stuinsertET5=0x7f080033;
        public static final int stuinsertET6=0x7f080032;
        public static final int stuinsertET7=0x7f080031;
        public static final int stuinsertET8=0x7f080030;
        public static final int stuinsertTV0=0x7f08002a;
        public static final int stuinsertTV1=0x7f08002c;
        public static final int stuinsertTV2=0x7f08002e;
        public static final int stuinsertTV3=0x7f08003b;
        public static final int stuinsertTV4=0x7f08002b;
        public static final int stuinsertTV5=0x7f08003a;
        public static final int stuinsertTV6=0x7f080039;
        public static final int stuinsertTV7=0x7f080038;
        public static final int stuinsertTV8=0x7f080037;
        public static final int stuinsertbtn=0x7f08002f;
        public static final int stuselectET=0x7f08005f;
        public static final int stuselectTV2=0x7f08005e;
        public static final int stuselectTV3=0x7f080061;
        public static final int stuselectbtn=0x7f080060;
        public static final int stustuselectETcTV1=0x7f08005d;
        public static final int stuupdateET1=0x7f080080;
        public static final int stuupdateET2=0x7f08007d;
        public static final int stuupdateET3=0x7f08007e;
        public static final int stuupdateET4=0x7f08007f;
        public static final int stuupdateET5=0x7f080079;
        public static final int stuupdateET6=0x7f080078;
        public static final int stuupdateET7=0x7f08007a;
        public static final int stuupdateET8=0x7f08007b;
        public static final int stuupdateTV0=0x7f080077;
        public static final int stuupdateTV1=0x7f080076;
        public static final int stuupdateTV2=0x7f08007c;
        public static final int stuupdateTV3=0x7f080081;
        public static final int stuupdateTV5=0x7f080083;
        public static final int stuupdateTV6=0x7f080084;
        public static final int stuupdateTV7=0x7f080082;
        public static final int stuupdateTV8=0x7f080085;
        public static final int stuupdatebtn=0x7f080086;
        public static final int teacher_detail=0x7f080067;
        public static final int teadeleteET=0x7f08000d;
        public static final int teadeleteTV1=0x7f08000b;
        public static final int teadeleteTV2=0x7f08000c;
        public static final int teadeletebtn=0x7f08000e;
        public static final int teainsertET1=0x7f08003f;
        public static final int teainsertET2=0x7f080045;
        public static final int teainsertET3=0x7f080044;
        public static final int teainsertET4=0x7f080043;
        public static final int teainsertET5=0x7f080042;
        public static final int teainsertTV0=0x7f08003c;
        public static final int teainsertTV1=0x7f08003e;
        public static final int teainsertTV2=0x7f080040;
        public static final int teainsertTV3=0x7f080047;
        public static final int teainsertTV4=0x7f08003d;
        public static final int teainsertTV5=0x7f080046;
        public static final int teainsertbtn=0x7f080041;
        public static final int teaselectET=0x7f080064;
        public static final int teaselectTV2=0x7f080063;
        public static final int teaselectTV3=0x7f080066;
        public static final int teaselectbtn=0x7f080065;
        public static final int teateaselectETcTV1=0x7f080062;
        public static final int teaupdateET1=0x7f08008d;
        public static final int teaupdateET2=0x7f08008a;
        public static final int teaupdateET3=0x7f08008b;
        public static final int teaupdateET4=0x7f08008c;
        public static final int teaupdateET5=0x7f080091;
        public static final int teaupdateTV0=0x7f080088;
        public static final int teaupdateTV1=0x7f080087;
        public static final int teaupdateTV2=0x7f080089;
        public static final int teaupdateTV3=0x7f08008e;
        public static final int teaupdateTV5=0x7f080090;
        public static final int teaupdateTV7=0x7f08008f;
        public static final int teaupdatebtn=0x7f080092;
        public static final int text=0x7f080048;
        public static final int title=0x7f080000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int cours_detail=0x7f030001;
        public static final int delete_cours=0x7f030002;
        public static final int delete_stu=0x7f030003;
        public static final int delete_tea=0x7f030004;
        public static final int info_handle=0x7f030005;
        public static final int insert_cours=0x7f030006;
        public static final int insert_stu=0x7f030007;
        public static final int insert_tea=0x7f030008;
        public static final int list_item=0x7f030009;
        public static final int login=0x7f03000a;
        public static final int main=0x7f03000b;
        public static final int my_cours=0x7f03000c;
        public static final int select_cours=0x7f03000d;
        public static final int select_cours_tip=0x7f03000e;
        public static final int select_cours_two=0x7f03000f;
        public static final int select_stu=0x7f030010;
        public static final int select_tea=0x7f030011;
        public static final int show_cours=0x7f030012;
        public static final int show_teacher=0x7f030013;
        public static final int teacher_detail=0x7f030014;
        public static final int update_cours=0x7f030015;
        public static final int update_stu=0x7f030016;
        public static final int update_tea=0x7f030017;
    }
    public static final class menu {
        public static final int cours_detail=0x7f070000;
        public static final int delete_cours=0x7f070001;
        public static final int delete_tea=0x7f070002;
        public static final int info_handle=0x7f070003;
        public static final int insert_cours=0x7f070004;
        public static final int insert_tea=0x7f070005;
        public static final int login=0x7f070006;
        public static final int main=0x7f070007;
        public static final int my_cours=0x7f070008;
        public static final int select_cours=0x7f070009;
        public static final int select_cours_tip=0x7f07000a;
        public static final int select_tea=0x7f07000b;
        public static final int show_cours=0x7f07000c;
        public static final int show_teacher=0x7f07000d;
        public static final int teacher_detail=0x7f07000e;
        public static final int update_cours=0x7f07000f;
        public static final int update_tea=0x7f070010;
    }
    public static final class string {
        public static final int action_settings=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int hello_world=0x7f050002;
        public static final int title_activity_cours_detail=0x7f050012;
        public static final int title_activity_delete_cours=0x7f05000e;
        public static final int title_activity_delete_tea=0x7f05000a;
        public static final int title_activity_info_handle=0x7f050009;
        public static final int title_activity_insert_cours=0x7f050010;
        public static final int title_activity_insert_tea=0x7f05000b;
        public static final int title_activity_login=0x7f050008;
        public static final int title_activity_main=0x7f05000f;
        public static final int title_activity_my_cours=0x7f050005;
        public static final int title_activity_select_cours=0x7f050006;
        public static final int title_activity_select_cours_tip=0x7f050007;
        public static final int title_activity_select_tea=0x7f05000c;
        public static final int title_activity_show_cours=0x7f050003;
        public static final int title_activity_show_teacher=0x7f050004;
        public static final int title_activity_teacher_detail=0x7f050013;
        public static final int title_activity_update_cours=0x7f050011;
        public static final int title_activity_update_tea=0x7f05000d;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060004;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060005;
        /**  全屏幕拉伸
         */
        public static final int layout_full=0x7f060000;
        /**  横向分布
         */
        public static final int layout_horizontal=0x7f060002;
        /**  纵向分布
         */
        public static final int layout_vertical=0x7f060003;
        /**  固定自身大小
         */
        public static final int layout_wrap=0x7f060001;
    }
}
